<a href="https://colab.research.google.com/github/Amarsinh0/BASICS-OF-PANDA/blob/main/kill_panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the module
import pandas as pd
import numpy as np


# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
							'Mahindra', 'Maruti', 'Hyundai',
							'Renault', 'Tata', 'Maruti'],
					'Year': [2012, 2014, 2011, 2015, 2012,
							2016, 2014, 2018, 2019],
					'Kms Driven': [50000, 30000, 60000,
									25000, None, 46000,
									31000, 15000, 12000],
					'City': ['Gurgaon', 'Delhi', 'Mumbai',
							'Delhi', None, 'Delhi',
							'Mumbai', 'Chennai', 'Ghaziabad'],
					'Mileage': [28, 27, 25, 26, 28,
								29, 24, 21, None]})

data

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012     50000.0    Gurgaon     28.0
1   Hyundai  2014     30000.0      Delhi     27.0
2      Tata  2011     60000.0     Mumbai     25.0
3  Mahindra  2015     25000.0      Delhi     26.0
4    Maruti  2012         NaN       None     28.0
5   Hyundai  2016     46000.0      Delhi     29.0
6   Renault  2014     31000.0     Mumbai     24.0
7      Tata  2018     15000.0    Chennai     21.0
8    Maruti  2019     12000.0  Ghaziabad      NaN

In [ ]:
df = data.set_index('Brand')
df

          Year  Kms Driven       City  Mileage
Brand
Maruti    2012     50000.0    Gurgaon     28.0
Hyundai   2014     30000.0      Delhi     27.0
Tata      2011     60000.0     Mumbai     25.0
Mahindra  2015     25000.0      Delhi     26.0
Maruti    2012         NaN       None     28.0
Hyundai   2016     46000.0      Delhi     29.0
Renault   2014     31000.0     Mumbai     24.0
Tata      2018     15000.0    Chennai     21.0
Maruti    2019     12000.0  Ghaziabad      NaN

In [ ]:
y=data.sort_values("Brand",axis=0,ascending=True,na_position='last')

y

      Brand  Year  Kms Driven       City  Mileage
1   Hyundai  2014     30000.0      Delhi     27.0
5   Hyundai  2016     46000.0      Delhi     29.0
3  Mahindra  2015     25000.0      Delhi     26.0
0    Maruti  2012     50000.0    Gurgaon     28.0
4    Maruti  2012         NaN       None     28.0
8    Maruti  2019     12000.0  Ghaziabad      NaN
6   Renault  2014     31000.0     Mumbai     24.0
2      Tata  2011     60000.0     Mumbai     25.0
7      Tata  2018     15000.0    Chennai     21.0

In [ ]:
s=data.sort_values(["Brand","Year"],axis=0, ascending=True)
s

      Brand  Year  Kms Driven       City  Mileage
1   Hyundai  2014     30000.0      Delhi     27.0
5   Hyundai  2016     46000.0      Delhi     29.0
3  Mahindra  2015     25000.0      Delhi     26.0
0    Maruti  2012     50000.0    Gurgaon     28.0
4    Maruti  2012         NaN       None     28.0
8    Maruti  2019     12000.0  Ghaziabad      NaN
6   Renault  2014     31000.0     Mumbai     24.0
2      Tata  2011     60000.0     Mumbai     25.0
7      Tata  2018     15000.0    Chennai     21.0

# group **by**

In [ ]:

print(data.groupby("Brand").groups)

{'Hyundai': [1, 5], 'Mahindra': [3], 'Maruti': [0, 4, 8], 'Renault': [6], 'Tata': [2, 7]}

In [ ]:
print(data.groupby(['Brand','Year']).groups)

{('Hyundai', 2014): [1], ('Hyundai', 2016): [5], ('Mahindra', 2015): [3], ('Maruti', 2012): [0, 4], ('Maruti', 2019): [8], ('Renault', 2014): [6], ('Tata', 2011): [2], ('Tata', 2018): [7]}

In [ ]:
data.groupby(["Brand"])["Mileage"].sum()

Brand
Hyundai     56.0
Mahindra    26.0
Maruti      56.0
Renault     24.0
Tata        46.0
Name: Mileage, dtype: float64

**aggregation**

In [ ]:
y= data.groupby(["Brand","Mileage"])
y.aggregate(np.sum)

<ipython-input-139-d09bcf204376>:2: FutureWarning: The operation <function sum at 0x7f7fbe9d0310> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  y.aggregate(np.sum)

                  Year  Kms Driven
Brand    Mileage
Hyundai  27.0     2014     30000.0
         29.0     2016     46000.0
Mahindra 26.0     2015     25000.0
Maruti   28.0     4024     50000.0
Renault  24.0     2014     31000.0
Tata     21.0     2018     15000.0
         25.0     2011     60000.0

In [ ]:
x=data.groupby("Brand")
x['Mileage'].agg([np.sum,np.mean,np.std,np.var])

           sum  mean       std  var
Brand
Hyundai   56.0  28.0  1.414214  2.0
Mahindra  26.0  26.0       NaN  NaN
Maruti    56.0  28.0  0.000000  0.0
Renault   24.0  24.0       NaN  NaN
Tata      46.0  23.0  2.828427  8.0

**transformation**

In [ ]:
df=pd.DataFrame({'p':range(4),'q':range(2,6)})
df

   p  q
0  0  2
1  1  3
2  2  4
3  3  5

In [ ]:
df.transform(lambda x:x+2)

   p  q
0  2  4
1  3  5
2  4  6
3  5  7

In [ ]:
s=pd.Series(range(4))
s

0    0
1    1
2    2
3    3
dtype: int64

In [ ]:
s.transform([np.sqrt,np.exp])

       sqrt        exp
0  0.000000   1.000000
1  1.000000   2.718282
2  1.414214   7.389056
3  1.732051  20.085537

In [ ]:
import pandas as pd
ser=pd.Series()
print(ser)

Series([], dtype: float64)

<ipython-input-145-023d9e7f7c92>:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  ser=pd.Series()

In [ ]:
import pandas as pd
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [ ]:

list=['a','b']
df=pd.DataFrame(list)
print(df)

   0
0  a
1  b

In [ ]:
import numpy as np
data=np.array(['a','b'])
print(data)

['a' 'b']

In [ ]:
data={"name":['rushi','vishal'],
      "age":[22,24]}
d=pd.DataFrame(data)
print(d)

     name  age
0   rushi   22
1  vishal   24

In [ ]:
# importing the module
import pandas as pd
import numpy as np


# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
							'Mahindra', 'Maruti', 'Hyundai',
							'Renault', 'Tata', 'Maruti'],
					'Year': [2012, 2014, 2011, 2015, 2012,
							2016, 2014, 2018, 2019],
					'Kms Driven': [50000, 30000, 60000,
									25000, None, 46000,
									31000, 15000, 12000],
					'City': ['Gurgaon', 'Delhi', 'Mumbai',
							'Delhi', None, 'Delhi',
							'Mumbai', 'Chennai', 'Ghaziabad'],
					'Mileage': [28, 27, 25, 26, 28,
								29, 24, 21, None]})

data

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012     50000.0    Gurgaon     28.0
1   Hyundai  2014     30000.0      Delhi     27.0
2      Tata  2011     60000.0     Mumbai     25.0
3  Mahindra  2015     25000.0      Delhi     26.0
4    Maruti  2012         NaN       None     28.0
5   Hyundai  2016     46000.0      Delhi     29.0
6   Renault  2014     31000.0     Mumbai     24.0
7      Tata  2018     15000.0    Chennai     21.0
8    Maruti  2019     12000.0  Ghaziabad      NaN

In [ ]:
S=data["Brand"]
S

0      Maruti
1     Hyundai
2        Tata
3    Mahindra
4      Maruti
5     Hyundai
6     Renault
7        Tata
8      Maruti
Name: Brand, dtype: object

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Brand       9 non-null      object
 1   Year        9 non-null      int64
 2   Kms Driven  8 non-null      float64
 3   City        8 non-null      object
 4   Mileage     8 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 488.0+ bytes

In [ ]:
data.describe()

              Year    Kms Driven    Mileage
count     9.000000      8.000000   8.000000
mean   2014.555556  33625.000000  26.000000
std       2.743680  17012.075543   2.618615
min    2011.000000  12000.000000  21.000000
25%    2012.000000  22500.000000  24.750000
50%    2014.000000  30500.000000  26.500000
75%    2016.000000  47000.000000  28.000000
max    2019.000000  60000.000000  29.000000

In [ ]:
y= data.drop("Brand",axis=1)
y

   Year  Kms Driven       City  Mileage
0  2012     50000.0    Gurgaon     28.0
1  2014     30000.0      Delhi     27.0
2  2011     60000.0     Mumbai     25.0
3  2015     25000.0      Delhi     26.0
4  2012         NaN       None     28.0
5  2016     46000.0      Delhi     29.0
6  2014     31000.0     Mumbai     24.0
7  2018     15000.0    Chennai     21.0
8  2019     12000.0  Ghaziabad      NaN

In [ ]:
print(data[['Year','City']])

   Year       City
0  2012    Gurgaon
1  2014      Delhi
2  2011     Mumbai
3  2015      Delhi
4  2012       None
5  2016      Delhi
6  2014     Mumbai
7  2018    Chennai
8  2019  Ghaziabad

In [ ]:
col=['a','b','c','d','e','f','g','h','i']
data['Address']=col
print(data)

      Brand  Year  Kms Driven       City  Mileage Address
0    Maruti  2012     50000.0    Gurgaon     28.0       a
1   Hyundai  2014     30000.0      Delhi     27.0       b
2      Tata  2011     60000.0     Mumbai     25.0       c
3  Mahindra  2015     25000.0      Delhi     26.0       d
4    Maruti  2012         NaN       None     28.0       e
5   Hyundai  2016     46000.0      Delhi     29.0       f
6   Renault  2014     31000.0     Mumbai     24.0       g
7      Tata  2018     15000.0    Chennai     21.0       h
8    Maruti  2019     12000.0  Ghaziabad      NaN       i

# **join()**

In [ ]:
a=df.join(df1)

a=df.join(df1,how='outer')

a=df.join(df1,how='inner')

a=df.join(df1,on='key')

In [ ]:
# importing the module
import pandas as pd
import numpy as np


# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
							'Mahindra', 'Maruti', 'Hyundai',
							'Renault', 'Tata', 'Maruti'],
					'Year': [2012, 2014, 2011, 2015, 2012,
							2016, 2014, 2018, 2019],
					'Kms Driven': [50000, 30000, 60000,
									25000, None, 46000,
									31000, 15000, 12000],
					'City': ['Gurgaon', 'Delhi', 'Mumbai',
							'Delhi', None, 'Delhi',
							'Mumbai', 'Chennai', 'Ghaziabad'],
					'Mileage': [28, 27, 25, 26, 28,
								29, 24, 21, None]})

data

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012     50000.0    Gurgaon     28.0
1   Hyundai  2014     30000.0      Delhi     27.0
2      Tata  2011     60000.0     Mumbai     25.0
3  Mahindra  2015     25000.0      Delhi     26.0
4    Maruti  2012         NaN       None     28.0
5   Hyundai  2016     46000.0      Delhi     29.0
6   Renault  2014     31000.0     Mumbai     24.0
7      Tata  2018     15000.0    Chennai     21.0
8    Maruti  2019     12000.0  Ghaziabad      NaN

In [ ]:
data.iloc[0]

Brand          Maruti
Year             2012
Kms Driven    50000.0
City          Gurgaon
Mileage          28.0
Name: 0, dtype: object

In [ ]:
data.iloc[2:5]

      Brand  Year  Kms Driven    City  Mileage
2      Tata  2011     60000.0  Mumbai     25.0
3  Mahindra  2015     25000.0   Delhi     26.0
4    Maruti  2012         NaN    None     28.0

In [ ]:
df=data.set_index('Brand')
df

          Year  Kms Driven       City  Mileage
Brand
Maruti    2012     50000.0    Gurgaon     28.0
Hyundai   2014     30000.0      Delhi     27.0
Tata      2011     60000.0     Mumbai     25.0
Mahindra  2015     25000.0      Delhi     26.0
Maruti    2012         NaN       None     28.0
Hyundai   2016     46000.0      Delhi     29.0
Renault   2014     31000.0     Mumbai     24.0
Tata      2018     15000.0    Chennai     21.0
Maruti    2019     12000.0  Ghaziabad      NaN

In [ ]:
x=df.loc[:,['Year','City']]
x

          Year       City
Brand
Maruti    2012    Gurgaon
Hyundai   2014      Delhi
Tata      2011     Mumbai
Mahindra  2015      Delhi
Maruti    2012       None
Hyundai   2016      Delhi
Renault   2014     Mumbai
Tata      2018    Chennai
Maruti    2019  Ghaziabad

In [ ]:
y=data[data.columns[1:3]]
y

   Year  Kms Driven
0  2012     50000.0
1  2014     30000.0
2  2011     60000.0
3  2015     25000.0
4  2012         NaN
5  2016     46000.0
6  2014     31000.0
7  2018     15000.0
8  2019     12000.0

In [ ]:
data.iloc[:,1:3]

   Year  Kms Driven
0  2012     50000.0
1  2014     30000.0
2  2011     60000.0
3  2015     25000.0
4  2012         NaN
5  2016     46000.0
6  2014     31000.0
7  2018     15000.0
8  2019     12000.0

In [ ]:
df.drop(["Tata","Mahindra"],inplace=True)
df

         Year  Kms Driven       City  Mileage
Brand
Maruti   2012     50000.0    Gurgaon     28.0
Hyundai  2014     30000.0      Delhi     27.0
Maruti   2012         NaN       None     28.0
Hyundai  2016     46000.0      Delhi     29.0
Renault  2014     31000.0     Mumbai     24.0
Maruti   2019     12000.0  Ghaziabad      NaN

In [ ]:
new=pd.DataFrame(['ferari'])
df=pd.concat([new,df]).reset_index(drop=True)
df

        0    Year  Kms Driven       City    Mileage
0  ferari     NaN         NaN        NaN        NaN
1     NaN  2012.0     50000.0    Gurgaon       28.0
2     NaN  2014.0     30000.0      Delhi       27.0
3     NaN  2012.0         NaN       None       28.0
4     NaN  2016.0     46000.0      Delhi       29.0
5     NaN  2014.0     31000.0     Mumbai       24.0
6     NaN  2019.0     12000.0  Ghaziabad  not avail

In [ ]:
x=df.loc['Renault']
y=df.loc['Tata']
print(x,'\n\n\n',y)

Year             2014
Kms Driven    31000.0
City           Mumbai
Mileage          24.0
Name: Renault, dtype: object


        Year  Kms Driven     City  Mileage
Brand
Tata   2011     60000.0   Mumbai     25.0
Tata   2018     15000.0  Chennai     21.0

In [240]:
df.drop(["Renault","Tata"],axis=0,inplace=True)
df

KeyError: ignored

In [ ]:
df=pd.DataFrame()
index=pd.date_range("2010-10-09 08:45",periods=9,freq='H')
df.index=index
print(df)

Empty DataFrame
Columns: []
Index: [2010-10-09 08:45:00, 2010-10-09 09:45:00, 2010-10-09 10:45:00, 2010-10-09 11:45:00, 2010-10-09 12:45:00, 2010-10-09 13:45:00, 2010-10-09 14:45:00, 2010-10-09 15:45:00, 2010-10-09 16:45:00]

In [ ]:
result=df.truncate(before='2010-10-09 9:45:00',after =' 2010-10-09 16:45:00')
print(result)

Empty DataFrame
Columns: []
Index: [2010-10-09 09:45:00, 2010-10-09 10:45:00, 2010-10-09 11:45:00, 2010-10-09 12:45:00, 2010-10-09 13:45:00, 2010-10-09 14:45:00, 2010-10-09 15:45:00, 2010-10-09 16:45:00]

In [ ]:
df.isnull()

          Year  Kms Driven   City  Mileage
Brand
Maruti   False       False  False    False
Hyundai  False       False  False    False
Maruti   False        True   True    False
Hyundai  False       False  False    False
Renault  False       False  False    False
Maruti   False       False  False     True

In [ ]:
df.isnull().sum()

Year          0
Kms Driven    1
City          1
Mileage       1
dtype: int64

In [ ]:
df.notnull()

         Year  Kms Driven   City  Mileage
Brand
Maruti   True        True   True     True
Hyundai  True        True   True     True
Maruti   True       False  False     True
Hyundai  True        True   True     True
Renault  True        True   True     True
Maruti   True        True   True    False

In [ ]:
df.fillna(0)

         Year  Kms Driven       City    Mileage
Brand
Maruti   2012     50000.0    Gurgaon       28.0
Hyundai  2014     30000.0      Delhi       27.0
Maruti   2012         0.0          0       28.0
Hyundai  2016     46000.0      Delhi       29.0
Renault  2014     31000.0     Mumbai       24.0
Maruti   2019     12000.0  Ghaziabad  not avail

In [ ]:
df.fillna(method='pad')

         Year  Kms Driven       City  Mileage
Brand
Maruti   2012     50000.0    Gurgaon     28.0
Hyundai  2014     30000.0      Delhi     27.0
Maruti   2012     30000.0      Delhi     28.0
Hyundai  2016     46000.0      Delhi     29.0
Renault  2014     31000.0     Mumbai     24.0
Maruti   2019     12000.0  Ghaziabad     24.0

In [ ]:
df.fillna(method="bfill")

         Year  Kms Driven       City  Mileage
Brand
Maruti   2012     50000.0    Gurgaon     28.0
Hyundai  2014     30000.0      Delhi     27.0
Maruti   2012     46000.0      Delhi     28.0
Hyundai  2016     46000.0      Delhi     29.0
Renault  2014     31000.0     Mumbai     24.0
Maruti   2019     12000.0  Ghaziabad      NaN

In [ ]:
df['Mileage'].fillna('no_mile',inplace=True)
df

         Year  Kms Driven       City    Mileage
Brand
Maruti   2012     50000.0    Gurgaon       28.0
Hyundai  2014     30000.0      Delhi       27.0
Maruti   2012         NaN       None       28.0
Hyundai  2016     46000.0      Delhi       29.0
Renault  2014     31000.0     Mumbai       24.0
Maruti   2019     12000.0  Ghaziabad  not avail

In [248]:
df.replace(to_replace=np.nan,value=00.0)

        0    Year  Kms Driven       City    Mileage
0  ferari     0.0         0.0        0.0        0.0
1     0.0  2012.0     50000.0    Gurgaon       28.0
2     0.0  2014.0     30000.0      Delhi       27.0
3     0.0  2012.0         0.0        0.0       28.0
4     0.0  2016.0     46000.0      Delhi       29.0
5     0.0  2014.0     31000.0     Mumbai       24.0
6     0.0  2019.0     12000.0  Ghaziabad  not avail

In [241]:
df.interpolate(method='linear',limit_direction='forward')

        0    Year  Kms Driven       City    Mileage
0  ferari     NaN         NaN        NaN        NaN
1     NaN  2012.0     50000.0    Gurgaon       28.0
2     NaN  2014.0     30000.0      Delhi       27.0
3     NaN  2012.0     38000.0       None       28.0
4     NaN  2016.0     46000.0      Delhi       29.0
5     NaN  2014.0     31000.0     Mumbai       24.0
6     NaN  2019.0     12000.0  Ghaziabad  not avail

In [242]:
df.interpolate(method='linear',limit_direction='backward')

        0    Year  Kms Driven       City    Mileage
0  ferari  2012.0     50000.0        NaN        NaN
1     NaN  2012.0     50000.0    Gurgaon       28.0
2     NaN  2014.0     30000.0      Delhi       27.0
3     NaN  2012.0     38000.0       None       28.0
4     NaN  2016.0     46000.0      Delhi       29.0
5     NaN  2014.0     31000.0     Mumbai       24.0
6     NaN  2019.0     12000.0  Ghaziabad  not avail

In [249]:
# importing the module
import pandas as pd
import numpy as np


# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
							'Mahindra', 'Maruti', 'Hyundai',
							'Renault', 'Tata', 'Maruti'],
					'Year': [2012, 2014, 2011, 2015, 2012,
							2016, 2014, 2018, 2019],
					'Kms Driven': [50000, 30000, 60000,
									25000, None, 46000,
									31000, 15000, 12000],
					'City': ['Gurgaon', 'Delhi', 'Mumbai',
							'Delhi', None, 'Delhi',
							'Mumbai', 'Chennai', 'Ghaziabad'],
					'Mileage': [28, 27, 25, 26, 28,
								29, 24, 21, None]})

data

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012     50000.0    Gurgaon     28.0
1   Hyundai  2014     30000.0      Delhi     27.0
2      Tata  2011     60000.0     Mumbai     25.0
3  Mahindra  2015     25000.0      Delhi     26.0
4    Maruti  2012         NaN       None     28.0
5   Hyundai  2016     46000.0      Delhi     29.0
6   Renault  2014     31000.0     Mumbai     24.0
7      Tata  2018     15000.0    Chennai     21.0
8    Maruti  2019     12000.0  Ghaziabad      NaN

In [250]:
data.dropna(how='all')

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012     50000.0    Gurgaon     28.0
1   Hyundai  2014     30000.0      Delhi     27.0
2      Tata  2011     60000.0     Mumbai     25.0
3  Mahindra  2015     25000.0      Delhi     26.0
4    Maruti  2012         NaN       None     28.0
5   Hyundai  2016     46000.0      Delhi     29.0
6   Renault  2014     31000.0     Mumbai     24.0
7      Tata  2018     15000.0    Chennai     21.0
8    Maruti  2019     12000.0  Ghaziabad      NaN

In [251]:
data.dropna(how='any')

      Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012     50000.0  Gurgaon     28.0
1   Hyundai  2014     30000.0    Delhi     27.0
2      Tata  2011     60000.0   Mumbai     25.0
3  Mahindra  2015     25000.0    Delhi     26.0
5   Hyundai  2016     46000.0    Delhi     29.0
6   Renault  2014     31000.0   Mumbai     24.0
7      Tata  2018     15000.0  Chennai     21.0

In [253]:
data.dropna(axis=1)

      Brand  Year
0    Maruti  2012
1   Hyundai  2014
2      Tata  2011
3  Mahindra  2015
4    Maruti  2012
5   Hyundai  2016
6   Renault  2014
7      Tata  2018
8    Maruti  2019

In [254]:
df=data.set_index('Brand')
df

          Year  Kms Driven       City  Mileage
Brand
Maruti    2012     50000.0    Gurgaon     28.0
Hyundai   2014     30000.0      Delhi     27.0
Tata      2011     60000.0     Mumbai     25.0
Mahindra  2015     25000.0      Delhi     26.0
Maruti    2012         NaN       None     28.0
Hyundai   2016     46000.0      Delhi     29.0
Renault   2014     31000.0     Mumbai     24.0
Tata      2018     15000.0    Chennai     21.0
Maruti    2019     12000.0  Ghaziabad      NaN

In [257]:
new_data=df.dropna(axis=0,how='any')
new_data

          Year  Kms Driven     City  Mileage
Brand
Maruti    2012     50000.0  Gurgaon     28.0
Hyundai   2014     30000.0    Delhi     27.0
Tata      2011     60000.0   Mumbai     25.0
Mahindra  2015     25000.0    Delhi     26.0
Hyundai   2016     46000.0    Delhi     29.0
Renault   2014     31000.0   Mumbai     24.0
Tata      2018     15000.0  Chennai     21.0